let fs = require('fs');

// This is good for local dev environments, when it's better to
// store a projects environment variables in a .gitignore'd file
require('dotenv').config();

const targetPath = './frontend/environments/environment.ts';
const envConfigFile = `
// Autogenerated using set-env.ts (npm run config)
export const environment = {
  production: true,
  GOOGLE_MAP_API_KEY: '${process.env.GOOGLE_MAP_API_KEY}'
};
`;

fs.writeFile(targetPath, envConfigFile, function (err) {
  if (err) {
    console.log(err);
  }

  console.log(`Output generated at ${targetPath}`);
});
